//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class examenEntities : DbContext
    {
        public examenEntities()
            : base("name=examenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<INT_Clientes> INT_Clientes { get; set; }
        public virtual DbSet<INT_pedido> INT_pedido { get; set; }
        public virtual DbSet<INT_Tipocliente> INT_Tipocliente { get; set; }
        public virtual DbSet<INT_Venta> INT_Venta { get; set; }
    }
}
