//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INT_Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INT_Clientes()
        {
            this.INT_pedido = new HashSet<INT_pedido>();
        }
    
        public int cliRut { get; set; }
        public string cliNombre { get; set; }
        public string cliDApellido { get; set; }
        public string cliDireccion { get; set; }
        public Nullable<int> Tipocliente { get; set; }
    
        public virtual INT_Tipocliente INT_Tipocliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INT_pedido> INT_pedido { get; set; }
    }
}
