//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INT_pedido
    {
        public int pedidoId { get; set; }
        public Nullable<int> Cliente { get; set; }
        public Nullable<int> Producto { get; set; }
    
        public virtual INT_Clientes INT_Clientes { get; set; }
        public virtual INT_Venta INT_Venta { get; set; }
    }
}
