//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INT_Venta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INT_Venta()
        {
            this.INT_pedido = new HashSet<INT_pedido>();
        }
    
        public int ventId { get; set; }
        public string ventNombre { get; set; }
        public string ventCodigo { get; set; }
        public string ventFamilia { get; set; }
        public string ventPrecio { get; set; }
        public int ventDescuento { get; set; }
        public string ventDescripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INT_pedido> INT_pedido { get; set; }
    }
}
